# .github/workflows/release.yml

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust_version: 1.77
        ubuntu_version: [ 22.04, 20.04, 18.04, 16.04 ]
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker buildx build --build-arg="RUST_VERSION=${{ matrix.rust_version }}" --build-arg="UBUNTU_VERSION=${{ matrix.ubuntu_version }}" --platform=linux/amd64 -f ./docker/Dockerfile --output=. --target=output .
      - name: Rename binary
        run: mv output/proxy-client output/proxy-client-ubuntu-${{ matrix.ubuntu_version }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
